"use client";
import { useParams } from "next/navigation";
import Header from "../../../components/Header";
import Footer from "../../../components/Footer";
import WatchCard from "../../../components/WatchCard";
import { useWatches } from "../../../components/useWatches";
import { site } from "../../../data/site";
import { getWatchId } from "../../../lib/watchUtils";
export default function WatchDetailPage(){
 const params=useParams(); const routeId=Array.isArray(params?.id)?params.id[0]:params?.id; const {watches,loading}=useWatches(); const product=watches.find(w=>getWatchId(w)===routeId);
 if(loading)return <><Header/><main id="main-content" className="page-shell"><section className="page-hero"><p className="eyebrow">Collection</p><h1>Loading watch…</h1></section></main><Footer/></>;
 if(!product)return <><Header/><main id="main-content" className="page-shell"><section className="page-hero"><p className="eyebrow">Collection</p><h1>This reference is unavailable.</h1><p>Private sourcing is available on request.</p><a className="btn gold" href={`${site.whatsapp}?text=Hello%20JAD%20KRONO%2C%20I%20would%20like%20to%20request%20private%20sourcing.`} target="_blank" rel="noreferrer">Request Sourcing</a></section></main><Footer/></>;
 const gallery=product.gallery?.length?product.gallery:product.image?[product.image]:[]; const related=watches.filter(w=>getWatchId(w)!==getWatchId(product)).slice(0,3); const message=encodeURIComponent(`Hello JAD KRONO, I would like to enquire about ${product.brand} ${product.model}, ref. ${product.reference}.`);
 const schema={"@context":"https://schema.org","@type":"Product",name:`${product.brand} ${product.model}`,sku:product.reference,description:product.description,brand:{"@type":"Brand",name:product.brand},offers:{"@type":"Offer",url:`${site.domain}/collection/${getWatchId(product)}`,availability:product.status==="Available"?"https://schema.org/InStock":"https://schema.org/PreOrder",priceCurrency:"SGD"}};
 return <><Header/><main id="main-content" className="product-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="product-hero"><div className="product-gallery"><div className="main-watch-frame">{gallery[0]?<img src={gallery[0]} alt={`${product.brand} ${product.model}, ref. ${product.reference}`}/>:<div className="large-watch-placeholder"><img src="/assets/jad-krono-mark.png" alt=""/></div>}</div>{gallery.length>1?<div className="thumb-grid">{gallery.slice(1,4).map((img,i)=><div className="thumb" key={img}><img src={img} alt={`${product.brand} ${product.model} detail ${i+1}`}/></div>)}</div>:null}</div><div className="product-info"><p className="eyebrow">{product.brand}</p><h1>{product.model}</h1><h2>Ref. {product.reference}</h2><p>{product.description}</p><div className="product-status"><span>{product.status}</span><strong>{product.price}</strong></div><div className="detail-list"><div><span>Reference</span><strong>{product.reference}</strong></div><div><span>Year</span><strong>{product.year}</strong></div><div><span>Overall condition</span><strong>{product.condition}</strong></div><div><span>Box & papers</span><strong>{product.set}</strong></div><div><span>Case</span><strong>{product.specs?.case}</strong></div><div><span>Movement</span><strong>{product.specs?.movement}</strong></div><div><span>Material</span><strong>{product.specs?.material}</strong></div><div><span>Location</span><strong>Singapore</strong></div></div><div className="product-actions"><a className="btn gold" href={`${site.whatsapp}?text=${message}`} target="_blank" rel="noreferrer">Enquire via WhatsApp</a><a className="btn outline" href="/collection">Back to Collection</a></div></div></section>{related.length?<section className="section related-section"><div className="section-heading"><p className="eyebrow">Related</p><h2>Other references.</h2></div><div className="watch-grid">{related.map(w=><WatchCard key={getWatchId(w)} product={w}/>)}</div></section>:null}</main><Footer/></>;
}
